# Generated by Django 4.1.3 on 2022-12-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='accountNumber',
            field=models.CharField(default=1100010, max_length=255),
            preserve_default=False,
        ),
    ]
