# Generated by Django 4.1.5 on 2023-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_database_accountnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='pin',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
